export const PRIMARY_LIGHT = '#534bae'
export const PRIMARY_DARK = '#18227c'
export const LIGHT_GREY = '#EEE'
export const MID_GREY = '#CCC'
export const DARK_GREY = '#333'
export const STATUS_GOOD_COLOR = '#27ae60'
export const STATUS_BAD_COLOR = '#d35400'
export const RECORDING_IN_PROGRESS_COLOR = '#c0392b'
